name: Merge Develop into Master and Release

on:
  workflow_dispatch:
    inputs:
      merge_and_release:
        description: 'Merge develop into master and release'
        required: true
        default: false

jobs:
  merge_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Merge Develop into Master
      if: ${{ github.event.inputs.merge_and_release == 'true' }}
      run: |
        git fetch origin develop
        git checkout master
        git pull origin develop

    - name: Set Version Number
      if: ${{ github.event.inputs.merge_and_release == 'true' }}
      id: set-version
      run: echo "::set-output name=version::${{ github.event.inputs.version }}"

    - name: Release
      if: ${{ github.event.inputs.merge_and_release == 'true' }}
      run: |
        echo "Merging develop into master and releasing version ${{ steps.set-version.outputs.version }}"
        # Additional steps for your release process go here
