name: Deployment

on:
  workflow_dispatch:
    inputs:
      merge:
        description: 'Should branch be merged into master?'
        required: true
        default: 'False'
        type: boolean
      minor_or_major:
        description: 'is this a Major or Minor release'
        required: false
        default: 'Minor'
        type: choice
        options:
        - Major
        - Minor
      prod_or_stage:
        description: 'Deployment env'
        required: true
        default: 'Dev'
        type: choice
        options:
        - Dev
        - Stage
        - Production

jobs:
  minor_or_major:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Merge Develop into Master
      if: ${{ github.event.inputs.merge == 'true' }}
      run: |
        git fetch origin develop
        git checkout master
        git pull origin develop

    - name: Set Version Number
      if: ${{ github.event.inputs.merge == 'true' }}
      id: set-version
      run: echo "::set-output name=version::${{ github.event.inputs.version }}"

    - name: Release
      if: ${{ github.event.inputs.merge_and_release == 'true' }}
      run: |
        echo "Merging develop into master and releasing version ${{ steps.set-version.outputs.version }}"
        # Additional steps for your release process go here
